// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxusrwc0QWV6Sb_oPMcywQlWoNjIPStXY',
    appId: '1:151995107413:web:aa78c8f7b56da839756cdc',
    messagingSenderId: '151995107413',
    projectId: 'tiketpesawat-99dc8',
    authDomain: 'tiketpesawat-99dc8.firebaseapp.com',
    storageBucket: 'tiketpesawat-99dc8.firebasestorage.app',
    measurementId: 'G-YF949ZPR61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK3guRZ-iGs2wKgLpPrjtuTwll6Q1l3zc',
    appId: '1:151995107413:android:c96fa33f90502bc9756cdc',
    messagingSenderId: '151995107413',
    projectId: 'tiketpesawat-99dc8',
    storageBucket: 'tiketpesawat-99dc8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPRwc35JVhH-oaXaVLuSgpfFFWmGgdbI',
    appId: '1:151995107413:ios:4fad1abcebb267fe756cdc',
    messagingSenderId: '151995107413',
    projectId: 'tiketpesawat-99dc8',
    storageBucket: 'tiketpesawat-99dc8.firebasestorage.app',
    iosBundleId: 'com.example.uasTiketpesawat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqPRwc35JVhH-oaXaVLuSgpfFFWmGgdbI',
    appId: '1:151995107413:ios:4fad1abcebb267fe756cdc',
    messagingSenderId: '151995107413',
    projectId: 'tiketpesawat-99dc8',
    storageBucket: 'tiketpesawat-99dc8.firebasestorage.app',
    iosBundleId: 'com.example.uasTiketpesawat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxusrwc0QWV6Sb_oPMcywQlWoNjIPStXY',
    appId: '1:151995107413:web:f57b73cfa632db89756cdc',
    messagingSenderId: '151995107413',
    projectId: 'tiketpesawat-99dc8',
    authDomain: 'tiketpesawat-99dc8.firebaseapp.com',
    storageBucket: 'tiketpesawat-99dc8.firebasestorage.app',
    measurementId: 'G-G7LWDBG5BB',
  );
}
